spring:
  datasource:
    url: jdbc:mysql://49.233.61.112:3306/ratel-boot?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
    username: root
    password: Kuan198885@222
  #配置 Jpa
  jpa:
    hibernate:
      # 生产环境设置成 none，避免程序运行时自动更新数据库结构 update
      ddl-auto: none

ratel:
  log:
    basePath: /Users/dongchuang/Downloads/logs

  modules:
    security:
      conf:
        permission: true
      # 文件存储路径
      file:
        path: /data/nginx/jsth/app/file/
        avatar: /data/nginx/jsth/app/avatar/
        jarHtml: classpath:/html/  # none - 代表不实用jar包 中的静态文件
        html: /data/rate_app/file/html/
        #  jarHtml: none  #classpath:/html/  # none - 代表不实用jar包 中的静态文件
        #  html: D:\code\yn_yq\rtadmin-server\rtadmin-run\src\main\resources\html\