spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ratel-framework?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
    username: root
    password: Dongsiqi#12
  #配置 Jpa
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: update # 生产环境设置成 none，避免程序运行时自动更新数据库结构 update

ratel:
  log:
    basePath: /Users/dongchuang/Downloads/logs
  modules:
    security:
      conf:
        permission: true
      # 文件存储路径
      file:
        path: /Users/dongchuang/Downloads/rtadmin/file/
        avatar: /Users/dongchuang/Downloads/rtadmin/avatar/
        jarHtml: classpath:/html/  # none - 代表不实用jar包 中的静态文件
        html: /data/rate_app/file/html/




